### PR TITLE
Bump version from 0.1.0 to 0.2.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by frankfu03**

### CODE REVIEW

**Comment by lbodor** [comment]
Are there any changes in this repo? We don't need igs site log bindings anymore. I know there is a dependency still on it in gws-core, but do we need to update the version?

**Comment by frankfu03** [comment]
If it is not used any more, we may just leave as it is and also remove it from the dependencies of geodesy-web-services.

**Comment by lbodor** [comment]
Let's remove it from gws-core as part of a separate change.

**Comment by frankfu03** [comment]
Good. I'll close this PR and remove it in a separate one.

**Comment by lbodor** [comment]
ok

**Pull request closed without merging**
